### ISSUE TITLE
6 moderate severity vulnerabilities!

### ISSUE THREAD

**Issue by Wheatttttttttttley** [Wheatttttttttttley/TicTacToe#1]
I deleted node_modules that came with `npx create-react-app my-app --template typescript`.
Then, I ran `npm install` and got these warnings.
```
nth-check  <2.0.1
Severity: moderate
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@2.1.3, which is a breaking change
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          node_modules/react-scripts

6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

Using `npm audit fix --force` is not helpful at all. It's going to cause more vulnerabilities. I'm not so sure what happened.

**Comment by simurgh9** [comment]
I have got the same issue, the reason `npm audit fix --force` causes more issues is that for some reason it downgrades `react-scripts` from `5.0.0` to `2.1.3`.

**Comment by Wheatttttttttttley** [comment]
So, we can't do anything here? 😢

**Comment by simurgh9** [comment]
I think [this](https://github.com/facebook/create-react-app/issues/11174) is what you're `oughta do.

**Comment by Wheatttttttttttley** [comment]
> I think [this](https://github.com/facebook/create-react-app/issues/11174) is what you're `oughta do.

Alright, thank you. 😊

**Comment by varun2013** [comment]
Is there any salutation to resolve it
